server:
  port: 8090

spring:
  banner:
    image:
      location: "banner.gif"
      width: 76
      height: 20

insurer:
  check: true
  check-types:
    - enabled: true
      type: "auto"
      description: "Автомобиль"
    - enabled: false
      type: "insured"
      description: "Застрахованные"